This program reads a mail from =stdin=, and copy it to your
Gmail account(or any other IMAP account);

* Getting started
#+begin_src sh
env USERNAME=myname@gmail.com PASSWORD=secret ./copy2gmail important < ~/.maildir/cur/test.mail
#+end_src

This command will login the gmail via IMAP with the given credentials,
and copy the mail in that file into the Gmail folder ~important~. The
folder will be created automatically if it does not exist.

* Folder mapping
  You can edit the ~folder2tags~ function in ~src/Main.hs~. The
  parameter ~f~ is the folder name from command line; the function
  should return a list of folder names the mail should be copied into.
  Return ~[]~ if you want to drop the mail.

  Most Gmail clients push notifications for only mails going into
  ~INBOX~, so in order to receive notifications for a mail, it should
  be copied into ~INBOX~.

  Don't worry about duplicates; IMAP folder is just Gmail tag, if you
  copy a mail into multiple folders, it will be a single mail with multiple tags. For
  example, if a mail is copied into ~important~ and ~INBOX~, then the
  mail will has two tags: ~important~ and ~INBOX~.

  The default ~folder2tags~ maps ~foo~ to ~[foo, INBOX]~; Here is
  another example:
  #+begin_src haskell
    folder2tags f =
      let f' = (T.unpack f) in
        -- drop the mail sent to v2ex@example.org
        if f' == "v2ex" then []
        -- mail sent to feed@riaqn.org will have the "feed" tag, but won't
        -- go into INBOX, so no notification
        else if f' == "feed" then [f]
        -- other mails(say, foo@riaqn.org) have both "foo" and "INBOX"
        -- tags, and push notification
        else [f, (T.pack "INBOX")]
  #+end_src
* Self hosted SMTP server
  If you have a domain name and SMTP server, and you want to store the
  mail on Gmail server instead of your own server, please continue
  reading.

  This section will show you how to configure Postfix hosting the
  domain ~riaqn.org~, so that all mails sent to ~@riaqn.org~ will be copied to
  your Gmail, with corresponding tags. For example, mails sent to
  ~haskell@riaqn.org~ will have the tag ~haskell~.

  Make sure ~riaqn.org~ is in your ~mydestination~ in ~main.cf~, so
  that mails sent to this domain will be handled by ~local_transport~.

  Add following lines into ~main.cf~:
  #+begin_example
    local_transport = copy2gmail
    copy2gmail_destination_recipient_limit = 1
  #+end_example

  Add following lines into ~master.cf~:
  #+begin_example 
    copy2gmail  unix  -       n       n       -       -       pipe
      flags=ODRhu user=riaqn argv=/bin/env USERNAME=myname@gmail.com PASSWORD=secret copy2gmail ${user}
  #+end_example
  You may want to make sure that ~copy2gmail~ is in your ~$PATH~

